language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO_VERSION=1.10.1
  - DJANGO_VERSION=1.9.9
  - DJANGO_VERSION=1.8.14
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest coveralls"
script:
  - coverage run --source=django_smalluuid ./tests/manage.py test
after_success:
  coveralls
