language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
env:
  - DJANGO_VERSION=1.8.2
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest coveralls"
script:
  - cd tests; coverage run manage.py test
after_success:
  coveralls
